import type { Metadata } from 'next'
import { Caveat, DM_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'
import './globals.css'
import { Header } from '@/components/header'

const caveat = Caveat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Antej-K',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn('font-caveat flex min-h-svh min-w-svw flex-col antialiased', caveat.style, dmSans.style)}
        style={{ backgroundImage: `url('/bg.jpg')` }}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
